Migrate to View binding, SDK 34 and Version catalogs
SimpleMobileTools/Simple-Music-Player pull request #592
Opened 2023-09-01 15:09 UTC by naveensingh

### Major changes:
 - Migrate build scripts from Groovy to [Kotlin DSL](https://developer.android.com/build/migrate-to-kotlin-dsl)
  - Migrate to [Gradle version catalogs](https://developer.android.com/build/migrate-to-catalogs)
 - Migrate from Kotlin Kapt to [KSP (Kotlin symbol processing)](https://developer.android.com/build/migrate-to-ksp) as Kapt is now in maintenance mode.
 - Migrate from Kotlin synthetics to [View binding](https://developer.android.com/topic/libraries/view-binding)
 - Target SDK 34:
   - Add `FOREGROUND_SERVICE_MEDIA_PLAYBACK` permission
   - _In progress..._

### Minor changes: 
 - Close track activity if the track is not found on third-party intents. Related issue: The commons function `getRealPathFromUri` used at third-party intents isn't working for files with download documents uri, I'll check it soon.
 - Fixed some minor adapter-related issues.

### Notes:
 - Since we need access to the currently initialized fragments in the main activity, I simply used the PagerAdapter API to store initialized fragments in a list. I didn't look for a novel solution since all this will be rewritten but let me know if I should.

2023-09-03 19:01 UTC, tibbi commented on app/src/main/kotlin/com/simplemobiletools/musicplayer/activities/MainActivity.kt
> +
useless empty line

2023-09-03 19:01 UTC, tibbi commented on app/src/main/kotlin/com/simplemobiletools/musicplayer/activities/QueueActivity.kt
> +
another useless line

2023-09-03 19:05 UTC, tibbi commented on app/src/main/kotlin/com/simplemobiletools/musicplayer/fragments/PlaylistsFragment.kt
> +
another line :)

2023-09-03 19:05 UTC, tibbi commented on app/src/main/kotlin/com/simplemobiletools/musicplayer/playback/MediaSessionCallback.kt
> +import com.simplemobiletools.musicplayer.helpers.log
accidental import

2023-09-03 19:06 UTC, tibbi commented
have you also tested upgrading from master branch in release mode?

2023-09-03 21:30 UTC, tibbi commented
selecting items like folders by long press and drag doesnt work

2023-09-04 03:53 UTC, naveensingh commented
> have you also tested upgrading from master branch in release mode?

No, I did some tests in release mode but not the migration one. Only tested the upgrade with debug builds, will check it now.
I'd tested migration in release mode at the time of media3 changes though

2023-09-04 03:53 UTC, naveensingh commented
> selecting items like folders by long press and drag doesnt work, only works at main tracks fragment

I'm on it...

2023-09-04 04:33 UTC, naveensingh commented
> selecting items like folders by long press and drag doesnt work, only works at main tracks fragment

I broke it :)

2023-09-04 06:32 UTC, naveensingh commented
> have you also tested upgrading from master branch in release mode?

did some basic testing, and nothing looks broken when upgrading from the last release in release mode

2023-09-04 15:10 UTC, naveensingh commented
Fix everything, check now, please.

2023-09-04 19:24 UTC, tibbi commented
if I have 1 playlist only and I long press it, it doesnt have the selected background. Albums opened from Artists tab dont have selected backgrounds either.

2023-09-05 02:23 UTC, naveensingh commented
> I have 1 playlist only and I long press it, it doesnt have the selected background

have you pulled the latest changes? I broke it during media3 changes and fixed it above https://github.com/SimpleMobileTools/Simple-Music-Player/pull/592/commits/bebd99bf5ff53a77ae0789e746e13fd10a92cf52

> Albums opened from Artists tab dont have selected backgrounds either

I remember that one never really worked and I kept ignoring it, I'm going to fix it now.

2023-09-05 07:19 UTC, tibbi commented
right, it works well now, but colors arent properly updated in onResume. The placeholder icon and selectiong texts either.

2023-09-05 07:46 UTC, naveensingh commented
Not sure what I need to do reproduce this.  I select some items   => go to home screen => reopen the app => everything is just as before

2023-09-05 07:50 UTC, tibbi commented
no need to select anything, just open the app settings, change colors and go back at the main screen

2023-09-05 09:43 UTC, naveensingh commented
Fixed the color issues and resolved some conflicts. I think the colors were not updated in some other apps with lists, will have to check.

2023-09-05 10:28 UTC, naveensingh commented
I didn't have any tracks without placeholders so didn't notice it, added now.

2023-09-05 12:27 UTC, tibbi commented
yeah looks good now, lets see how will it go ;) Thanks

2023-09-05 12:27 UTC, merged

2024-07-15 13:39 UTC, GregKruz requested changes
Spam